steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
images:
  - 'gcr.io/$PROJECT_ID/gcpdevops'
options:
  logging: NONE  # No logs stored (not recommended for debugging)git 